name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 运行 check.py
        run: python check.py

      - name: 运行 alter.py
        run: python alter.py

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装依赖
        run: npm install      
        
      - name: 生成导航菜单
        run: npm run generate-nav

      - name: 构建站点
        run: npm run build

      - name: 上传构建产物
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vitepress/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: 部署到 GitHub Pages
        uses: actions/deploy-pages@v1